### PR TITLE
Google analytics Page view tracking

### PR DESCRIPTION
**Pull request by musangowope**
- Add google analytics package
- Created component to detect pages send data to google analytics account
- create env to to reference GA tracking code
DEMO:
https://www.loom.com/share/123b413ff2884188a9c00244fb18ebbe

## Testing locally
Set up ngrok to portforward to port 3000
https://veneciacalista.medium.com/how-to-use-ngrok-for-react-84bf2acc3907

Create GA account
https://analytics.google.com/ and get tracking code
https://prnt.sc/1dwgt0u

create `.env` in root of project and add the following
```
REACT_APP_GA_TRACKING_CODE=tracking code

``` 
run application

### CODE REVIEW

**Comment by musangowope** [comment]
@longhotsummer this gets us started with tracking pages
https://github.com/laws-africa/constitution-app-react/issues/57

For more finite tracking we can use GA Events, but we need to discuss how to implement this

**Comment by longhotsummer** [comment]
Seems reasonable.

What are we tracking with this, and what are we missing (if anything)? Tracking every router change (ie. pageview) should be sufficient to start with.

When building and deploying the app, how do we inject the tracking ID? Is it possible to hardcode it in and then disable it when in development mode? Alternatively how do we inject it at build time?

**Comment by musangowope** [comment]
@longhotsummer updated to production GA tracking ID
Did testing. GA will not run when in local host so we don't need to include functionality to condition load GA

**Review by longhotsummer — CHANGES_REQUESTED** [review]
The .env file can fall away, then, right?

**Comment by musangowope** [comment]
> The .env file can fall away, then, right?
Yes. removed it now

**Review by longhotsummer — APPROVED** [review]

**Pull request merged**
